{{- if .Values.vmServiceScrape.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "domain-expiry-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "domain-expiry-exporter.labels" . | nindent 4 }}
    {{- with .Values.vmServiceScrape.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "domain-expiry-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.vmServiceScrape.interval }}
{{- end }}
